#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# APhO2026_E2_Sim -- EN edition, generated by build_editions.py.  Do not edit.

"""
APhO 2026 (Busan, Korea) — Experimental Problem 2
"Estimation of an unknown resistance with the Micro:bit ADC"
Virtual laboratory simulator.   HaslaLab / HaslaEdu

Single file, standard library only (tkinter).  Python 3.8+.

DESIGN PRINCIPLE (absolute):
    Nothing is computed for the student.  The only number that ever appears is
    the integer that the micro:bit scrolls across its 5x5 LED matrix, exactly
    as the real kit does.  No voltages, no resistances, no fitted values.
"""
import math
import random
import time
import tkinter as tk
from tkinter import messagebox

APP_TITLE = 'APhO 2026 Experiment 2 — Unknown resistance with the Micro:bit ADC (HaslaLab)'
VCC = 3.0
ADC_RIN = 10000000.0
ADC_MAX = 1023
R_SHORT = 50.0
R_LEAK = 1000000000000.0
PACKS = {'A': [('A%d' % i, 3300.0, 'band', None) for i in range(1, 11)], 'B': [('B1', 6800.0, 'band', None), ('B2', 560.0, 'band', None), ('B3', 4700.0, 'tube', '#3aa14d')], 'C': [('C1', 12000.0, 'band', None), ('C2', 1580.0, 'tube', '#2f6fd0'), ('C3', 235.0, 'tube', '#c8332b')], 'D': [('D1', 510000.0, 'band', None), ('D2', 680000.0, 'tube', '#1b1d21')]}
DEV_COL = ('#23262b', '#23262b', '#23262b')
DEV_EDGE = ('#111417', '#111417', '#111417')
DEV_NAME = ('#1', '#2', '#3')
PACK_LABEL = {'A': 'Set A : ten 3.3 kΩ', 'B': 'Set B : 6.8 kΩ, 560 Ω, unknown (green)', 'C': 'Set C : 12 kΩ, unknown (blue), unknown (red)', 'D': 'Set D : 510 kΩ, unknown (black)'}
TOL = 0.001
NCOL = 30
ROWS_L = 'ABCDE'
ROWS_R = 'FGHIJ'
RAILS = ('T+', 'T-', 'B+', 'B-')

def node_of(hole):
    """hole = ('L', col, row) | ('R', col, row) | ('rail', name, col)"""
    if hole[0] == 'rail':
        return ('rail', hole[1])
    return (hole[0], hole[1])

class Circuit(object):
    """resistor network on the breadboard, solved by nodal analysis."""

    def __init__(self):
        self.res = {}
        self.lead = {}

    def nodes(self):
        s = set()
        for h1, h2, _ in self.res.values():
            s.add(node_of(h1))
            s.add(node_of(h2))
        for h in self.lead.values():
            if h:
                s.add(node_of(h))
        return sorted(s, key=lambda t: (str(t[0]), str(t[1])))

    def solve(self, probe_loaded=True):
        """return (V_probe, V_of_node dict, I_supply) or None if not measurable."""
        hv, hg = (self.lead.get('vc'), self.lead.get('gnd'))
        if not hv or not hg:
            return None
        nv, ng = (node_of(hv), node_of(hg))
        if nv == ng:
            return 'short'
        nodes = self.nodes()
        idx = {n: i for i, n in enumerate(nodes)}
        n = len(nodes)
        G = [[0.0] * n for _ in range(n)]
        I = [0.0] * n

        def stamp(a, b, g):
            ia, ib = (idx[a], idx[b])
            G[ia][ia] += g
            G[ib][ib] += g
            G[ia][ib] -= g
            G[ib][ia] -= g
        for h1, h2, R in self.res.values():
            a, b = (node_of(h1), node_of(h2))
            if a == b:
                continue
            stamp(a, b, 1.0 / max(R, 1e-09))
        hp = self.lead.get('probe')
        if hp and probe_loaded:
            a = node_of(hp)
            if a != ng:
                stamp(a, ng, 1.0 / ADC_RIN)
        for a in nodes:
            if a != ng:
                G[idx[a]][idx[a]] += 1.0 / R_LEAK
        for fixed, val in ((nv, VCC), (ng, 0.0)):
            i = idx[fixed]
            for j in range(n):
                G[i][j] = 0.0
            G[i][i] = 1.0
            I[i] = val
        V = gauss(G, I)
        if V is None:
            return None
        volt = {nd: V[idx[nd]] for nd in nodes}
        isup = 0.0
        for h1, h2, R in self.res.values():
            a, b = (node_of(h1), node_of(h2))
            if a == nv and b != nv:
                isup += (volt[a] - volt[b]) / R
            elif b == nv and a != nv:
                isup += (volt[b] - volt[a]) / R
        if hp and probe_loaded and (node_of(hp) == nv):
            isup += volt[nv] / ADC_RIN
        if isup > VCC / R_SHORT:
            return 'short'
        vp = volt[node_of(hp)] if hp else None
        return (vp, volt, isup)

def gauss(A, b):
    n = len(b)
    M = [row[:] + [b[i]] for i, row in enumerate(A)]
    for c in range(n):
        p = max(range(c, n), key=lambda r: abs(M[r][c]))
        if abs(M[p][c]) < 1e-18:
            return None
        M[c], M[p] = (M[p], M[c])
        pv = M[c][c]
        for r in range(n):
            if r == c:
                continue
            f = M[r][c] / pv
            if f:
                for k in range(c, n + 1):
                    M[r][k] -= f * M[c][k]
    return [M[i][n] / M[i][i] for i in range(n)]

class Device(object):
    """one micro:bit.  Ideal linear mapping 0..Vc -> 0..1023 plus a small,
    device specific integral non-linearity and read noise."""

    def __init__(self, k, seed):
        rng = random.Random(1000 * seed + k)
        self.k = k
        self.gain = 1.0 + rng.uniform(-0.0012, 0.0012)
        self.off = rng.uniform(-0.45, 0.45)
        self.a = [rng.uniform(-1.6, 1.6), rng.uniform(-1.2, 1.2), rng.uniform(-0.9, 0.9)]
        self.noise = 0.3
        self.rng = rng
        self.dead = False

    def inl(self, u):
        return self.a[0] * math.sin(math.pi * u) + self.a[1] * math.sin(2 * math.pi * u) + self.a[2] * math.sin(3 * math.pi * u)

    def read(self, v):
        u = max(0.0, min(1.0, v / VCC))
        x = ADC_MAX * u * self.gain + self.off + self.inl(u) + self.rng.gauss(0.0, self.noise)
        return int(max(0, min(ADC_MAX, math.floor(x + 0.5))))

class World(object):

    def __init__(self, seed=None):
        seed = random.randrange(1 << 30) if seed is None else seed
        self.seed = seed
        self.rng = random.Random(seed)
        self.cir = Circuit()
        self.devices = [Device(k, seed) for k in range(3)]
        self.active = 0
        self.cells_free = 6
        self.cell_hand = 0
        self.cells = [0, 0, 0]
        self.batt_in = [False] * 3
        self.switch = [False] * 3
        self.spare_used = False
        self.jump = dict((i, {'hdr': None, 'hole': None}) for i in WIRES)
        self.msg = ''
        self.value = {}
        for pk, items in PACKS.items():
            for cid, nom, kind, col in items:
                self.value[cid] = nom * (1.0 + self.rng.uniform(-TOL, TOL))
        self.placed = {}
        self.taken = set()

    @property
    def power(self):
        """a kit runs only with two cells in its holder, the plug in and the
        slide switch on."""
        k = self.active
        return self.cells[k] == 2 and self.batt_in[k] and self.switch[k]

    @power.setter
    def power(self, v):
        """convenience used by the verification harness: set up (or shut down)
        every kit at once, exactly as if all six cells had been fitted."""
        for k in range(3):
            if v:
                take = min(2 - self.cells[k], self.cells_free)
                self.cells_free -= take
                self.cells[k] += take
            self.batt_in[k] = bool(v)
            self.switch[k] = bool(v)

    def cells_total(self):
        """six cells all told, wherever they happen to be."""
        return self.cells_free + sum(self.cells) + self.cell_hand

    def load_cell(self, k):
        """put one of the loose cells into holder k."""
        if self.cells_free <= 0 or self.cells[k] >= 2:
            return False
        self.cells_free -= 1
        self.cells[k] += 1
        return True

    def unload_cell(self, k):
        if self.cells[k] <= 0:
            return False
        self.cells[k] -= 1
        self.cells_free += 1
        return True

    @property
    def dev(self):
        return self.devices[self.active]

    def place(self, cid, h1, h2):
        self.placed[cid] = (h1, h2)
        self.cir.res[cid] = (h1, h2, self.value[cid])

    def remove(self, cid):
        self.placed.pop(cid, None)
        self.cir.res.pop(cid, None)

    def set_lead(self, which, hole):
        self.cir.lead[which] = hole

    def free_wire(self):
        for i in WIRES:
            j = self.jump[i]
            if not j['hdr'] and (not j['hole']):
                return i
        return None

    def wire_at_hdr(self, col, row):
        for i in WIRES:
            j = self.jump[i]
            if j['hdr'] and j['hdr'][0] == col and (j['hdr'][1] == row):
                return i
        return None

    def roles(self):
        """the V row is the supply, the G row the reference, the S row of
        column k is pin Pk."""
        r = {'vc': None, 'gnd': None, 'pin': {}}
        for i in WIRES:
            j = self.jump[i]
            if not j['hdr'] or not j['hole']:
                continue
            if j['hdr'][1] == 'V':
                r['vc'] = j['hole']
            elif j['hdr'][1] == 'G':
                r['gnd'] = j['hole']
            else:
                r['pin'][j['hdr'][0]] = j['hole']
        return r

    def measure(self, which='A'):
        """press button A: returns the integer the micro:bit scrolls, or a
        status string ('off', 'nowire', 'short', 'dead')."""
        if self.dev.dead:
            return 'dead'
        if not self.power:
            return 'off'
        R = self.roles()
        if not R['vc']:
            return 'novc'
        if not R['gnd']:
            return 'nognd'
        pin = BTN_PIN.get(which or 'A', 0)
        hp = R['pin'].get(pin)
        self.cir.lead = {'vc': R['vc'], 'gnd': R['gnd'], 'probe': hp}
        r = self.cir.solve()
        if r is None:
            return 'nowire'
        if r == 'short':
            self.dev.dead = True
            return 'short'
        vp, volt, isup = r
        # an input with nothing on it is not an error on real hardware: it
        # floats, and the converter returns whatever the leakage leaves
        if hp is None:
            return self.dev.read(self.rng.uniform(0.0, 0.06))
        if vp is None:
            return 'nowire'
        return self.dev.read(vp)
C_BG = '#1b1e24'
C_PANEL = '#22262d'
C_TXT = '#e8eef2'
C_ACC = '#f2c14e'
C_BOARD = '#e9e6dd'
C_BOARD2 = '#d6d2c6'
C_HOLE = '#2a2c2f'
C_RED = '#cc3b32'
C_BLUE = '#3363b8'
WIRE_SETS = ({'probe': '#f5d033', 'vc': '#e33d2e', 'gnd': '#23272e'}, {'probe': '#8b4fd0', 'vc': '#3fa85a', 'gnd': '#2f6fd0'}, {'probe': '#e6ebf0', 'vc': '#24b7c9', 'gnd': '#d94f8a'})
CASE_SETS = ({'probe': '#8a6f14', 'vc': '#8a231a', 'gnd': '#0c0e12'}, {'probe': '#4d2a75', 'vc': '#215c31', 'gnd': '#1b4079'}, {'probe': '#8f979e', 'vc': '#12707c', 'gnd': '#8a2d55'})
# each kit comes with its own battery lead, in colours no jumper of that
# kit uses, so a cable is never mistaken for a jumper
CABLE_SETS = ({'a': '#e6eaea', 'b': '#8d949b'}, {'a': '#cc3b32', 'b': '#1b1e22'}, {'a': '#1f8f9c', 'b': '#3a4048'})
C_WIRE = WIRE_SETS[2]
C_WIRE_CASE = CASE_SETS[2]
LEAD_LABEL = {'w1': 'jumper 1', 'w2': 'jumper 2', 'w3': 'jumper 3'}
# the expansion board breaks P0..P16 out as three header rows: S (the pin),
# V (3V) and G (0V).  analogReadPin works on P0-P4 and P10 and returns
# 0..1023 for 0..3 V; the kit program shows P0 on button A and P1 on B.
HDR_COLS = 17
HDR_ROWS = ('S', 'V', 'G')
ANALOG_PINS = (0, 1, 2, 3, 4, 10)
BTN_PIN = {'A': 0, 'B': 1}
WIRES = ('w1', 'w2', 'w3')
WIRE_KEY = {'w1': 'probe', 'w2': 'vc', 'w3': 'gnd'}
# control point and end of the stub a half-plugged jumper hangs by, one per
# wire so three of them never lie on top of each other
LOOSE_STUB = ((-16, 2, -30, 6), (-18, 10, -34, 18), (-20, 18, -38, 30))
TAKE_MSG = ' in hand - plug one end into a header, the other into the board.'
INTO_HDR = ' plugged into header '
INTO_BOARD = ' plugged into '
HDR_TAKEN = 'another jumper is already in that header.'
NO_FREE = 'all three jumpers are in use - click one to move it, right-click to pull it out.'
CARRY_TAIL = ' : click a header or a hole'
PULLED_OUT = ' pulled out.'
FLOAT_MSG = ' has nothing connected - the input floats and the value wanders.'
ARROW = ' <-> '

def hdr_name(col, row):
    return '3V' if row == 'V' else 'GND' if row == 'G' else 'P' + str(col)
P = 22.0
BX, BY = (52.0, 452.0)
ROW_Y = {'T+': 0.0, 'T-': 1.0, 'A': 2.9, 'B': 3.9, 'C': 4.9, 'D': 5.9, 'E': 6.9, 'F': 8.7, 'G': 9.7, 'H': 10.7, 'I': 11.7, 'J': 12.7, 'B+': 14.6, 'B-': 15.6}
FONT5 = {'0': ('01100', '10010', '10010', '10010', '01100'), '1': ('00100', '01100', '00100', '00100', '01110'), '2': ('11100', '00010', '01100', '10000', '11110'), '3': ('11110', '00010', '00100', '10010', '01100'), '4': ('00110', '01010', '10010', '11111', '00010'), '5': ('11111', '10000', '11110', '00001', '11110'), '6': ('00110', '01000', '11110', '10001', '01110'), '7': ('11111', '00010', '00100', '01000', '10000'), '8': ('01110', '10001', '01110', '10001', '01110'), '9': ('01110', '10001', '01111', '00010', '01100'), ' ': ('00000', '00000', '00000', '00000', '00000'), 'E': ('11111', '10000', '11110', '10000', '11111'), 'r': ('00000', '00000', '10110', '11000', '10000'), 'o': ('00000', '01100', '10010', '10010', '01100'), 'F': ('11111', '10000', '11110', '10000', '10000'), '-': ('00000', '00000', '11111', '00000', '00000'), '?': ('01110', '10001', '00110', '00000', '00100')}

def hole_pos(h):
    if h[0] == 'rail':
        return (BX + h[2] * P, BY + ROW_Y[h[1]] * P)
    return (BX + h[1] * P, BY + ROW_Y[h[2]] * P)

def all_holes():
    out = []
    for c in range(1, NCOL + 1):
        for r in ROWS_L:
            out.append(('L', c, r))
        for r in ROWS_R:
            out.append(('R', c, r))
        for nm in RAILS:
            out.append(('rail', nm, c))
    return out

class App(tk.Tk):

    def __init__(self, seed=None):
        tk.Tk.__init__(self)
        self.title(APP_TITLE)
        self.configure(bg=C_BG)
        self.geometry('1340x860')
        self.minsize(1120, 720)
        self.w = World(seed)
        self.zoom = 1.0
        self.pan = [0.0, 0.0]
        self.carry = None
        self.pending = None
        self.mouse = (0, 0)
        self.holes = all_holes()
        self.scroll = None
        self._tag = 'dyn'
        self._skey = None
        self.last_reading = None
        self.notes_text = None
        self._build_ui()
        self.t_prev = time.perf_counter()
        self.after(30, self._tick)

    def _build_ui(self):
        top = tk.Frame(self, bg=C_BG)
        top.pack(side='top', fill='x')
        tk.Label(top, text=APP_TITLE, bg=C_BG, fg=C_ACC, font=('Malgun Gothic', 12, 'bold')).pack(side='left', padx=10, pady=6)
        body = tk.Frame(self, bg=C_BG)
        body.pack(fill='both', expand=True)
        self.cv = tk.Canvas(body, bg=C_BG, highlightthickness=0)
        self.cv.pack(side='left', fill='both', expand=True)
        self.cv.bind('<Configure>', lambda e: self._fit())
        self.cv.bind('<Motion>', self.on_motion)
        self.cv.bind('<Button-1>', self.on_click)
        self.cv.bind('<Button-3>', self.on_rclick)
        self.cv.bind('<MouseWheel>', self.on_wheel)
        self.cv.bind('<Button-4>', lambda e: self.on_wheel(e, 1))
        self.cv.bind('<Button-5>', lambda e: self.on_wheel(e, -1))
        self.cv.bind('<ButtonPress-2>', self.on_pan_start)
        self.cv.bind('<B2-Motion>', self.on_pan)
        self.cv.bind('<B1-Motion>', self.on_pan_left)
        self.cv.bind('<ButtonRelease-1>', self.on_pan_left_end)
        right = tk.Frame(body, bg=C_BG, width=282)
        right.pack(side='right', fill='y')
        right.pack_propagate(False)
        kit = tk.LabelFrame(right, text=' Micro:bit kit ', bg=C_BG, fg=C_ACC, font=('Malgun Gothic', 9, 'bold'))
        kit.pack(fill='x', padx=8, pady=(8, 4))
        self.dev_var = tk.IntVar(value=0)
        for k in range(3):
            tk.Radiobutton(kit, text='connect Micro:bit #%d' % (k + 1), variable=self.dev_var, value=k, command=self.swap_device, bg=C_BG, fg=C_TXT, selectcolor='#12161b', activebackground=C_BG, activeforeground=C_ACC, font=('Malgun Gothic', 9)).pack(anchor='w', padx=8)
        tk.Label(kit, text='only one may be wired at a time', bg=C_BG, fg='#7b838b', font=('Malgun Gothic', 8), wraplength=250, justify='left').pack(anchor='w', padx=8, pady=(2, 6))
        pk = tk.LabelFrame(right, text=' Resistor sets ', bg=C_BG, fg=C_ACC, font=('Malgun Gothic', 9, 'bold'))
        pk.pack(fill='x', padx=8, pady=4)
        self.pack_btn = {}
        for key in ('A', 'B', 'C', 'D'):
            f = tk.Frame(pk, bg=C_BG)
            f.pack(fill='x', padx=6, pady=2)
            tk.Label(f, text=PACK_LABEL[key], bg=C_BG, fg='#aeb6bd', justify='left', font=('Malgun Gothic', 8), wraplength=250).pack(anchor='w')
            grid = tk.Frame(f, bg=C_BG)
            grid.pack(anchor='w', pady=(1, 3))
            for i, (cid, nom, kind, col) in enumerate(PACKS[key]):
                b = tk.Button(grid, text=self._chip_label(cid, nom, kind), width=7, bg=col or '#8b6d43' if kind == 'tube' else '#8b6d43', fg='white', relief='flat', font=('Consolas', 8), command=lambda c=cid: self.take_resistor(c))
                b.grid(row=i // 3, column=i % 3, padx=2, pady=1)
                self.pack_btn[cid] = b
        self.status = tk.Label(right, text='', bg='#12161b', fg=C_ACC, justify='left', anchor='nw', font=('Malgun Gothic', 9), wraplength=262)
        self.status.pack(fill='both', expand=True, padx=8, pady=8)

    def _chip_label(self, cid, nom, kind):
        if kind == 'tube':
            return '??'
        if nom >= 1000:
            return '%g k' % (nom / 1000.0)
        return '%g' % nom

    def _fit(self):
        W, H = (self.cv.winfo_width(), self.cv.winfo_height())
        if W < 30 or H < 30 or getattr(self, '_view_touched', False):
            return
        x0, y0, x1, y1 = (24.0, 24.0, BX + (NCOL + 2.6) * P, BY + 18.4 * P)
        self.zoom = min(W / (x1 - x0), H / (y1 - y0)) * 0.98
        self.pan = [(W - (x1 - x0) * self.zoom) / 2.0 - x0 * self.zoom, (H - (y1 - y0) * self.zoom) / 2.0 - y0 * self.zoom]

    def S(self, x, y):
        return (x * self.zoom + self.pan[0], y * self.zoom + self.pan[1])

    def inv(self, px, py):
        return ((px - self.pan[0]) / self.zoom, (py - self.pan[1]) / self.zoom)

    def nearest_hole(self, px, py, rmax=None):
        if rmax is None:
            rmax = max(P * 0.62, 14.0 / self.zoom)
        x, y = self.inv(px, py)
        best, bd = (None, 1000000000.0)
        for h in self.holes:
            hx, hy = hole_pos(h)
            d = (hx - x) ** 2 + (hy - y) ** 2
            if d < bd:
                best, bd = (h, d)
        return best if bd <= rmax * rmax else None

    def _static_key(self):
        w = self.w
        return (round(self.zoom, 4), round(self.pan[0], 2), round(self.pan[1], 2), self.cv.winfo_width(), self.cv.winfo_height(), w.active, tuple(w.cells), w.cells_free, tuple(w.batt_in), tuple(w.switch), tuple(sorted(w.placed.items())), tuple(sorted(((k, str(v)) for k, v in w.cir.lead.items()))), self.carry, self.pending, w.dev.dead, self.carry_cell)

    def draw(self):
        cv = self.cv
        W, H = (cv.winfo_width(), cv.winfo_height())
        key = self._static_key()
        if key != self._skey:
            self._skey = key
            cv.delete('all')
            self._tag = 'st'
            cv.create_rectangle(0, 0, W, H, fill=C_BG, outline='', tags='st')
            self._draw_bench()
            self._draw_breadboard()
            self._draw_microbit()
            self._draw_resistors()
            self._draw_wires()
        else:
            cv.delete('dyn')
        self._tag = 'dyn'
        self._draw_matrix()
        self._draw_carry()

    @property
    def carry_cell(self):
        return bool(self.w.cell_hand)

    @carry_cell.setter
    def carry_cell(self, v):
        self.w.cell_hand = 1 if v else 0

    def wire(self, key):
        return WIRE_SETS[self.w.active][WIRE_KEY.get(key, key)]

    def case(self, key):
        return CASE_SETS[self.w.active][WIRE_KEY.get(key, key)]

    def _tagged(self, kw):
        kw.setdefault('tags', getattr(self, '_tag', 'dyn'))
        return kw

    def _r(self, x0, y0, x1, y1, **kw):
        a = self.S(x0, y0)
        b = self.S(x1, y1)
        return self.cv.create_rectangle(a[0], a[1], b[0], b[1], **self._tagged(kw))

    def _t(self, x, y, txt, size=9, fill=C_TXT, anchor='nw', bold=False):
        a = self.S(x, y)
        f = ('Malgun Gothic', max(6, int(size * self.zoom)), 'bold' if bold else 'normal')
        return self.cv.create_text(a[0], a[1], text=txt, fill=fill, anchor=anchor, font=f, tags=getattr(self, '_tag', 'dyn'))

    def _draw_bench(self):
        self._r(24, 24, BX + (NCOL + 2.6) * P, BY + 18.4 * P, fill='#242830', outline='#2f3540')

    def _draw_breadboard(self):
        x0, y0 = (BX - 1.4 * P, BY - 1.2 * P)
        x1, y1 = (BX + (NCOL + 1.4) * P, BY + 16.9 * P)
        self._r(x0, y0, x1, y1, fill=C_BOARD, outline='#b9b4a6', width=2)
        for nm, col in (('T+', C_RED), ('T-', C_BLUE), ('B+', C_RED), ('B-', C_BLUE)):
            y = BY + ROW_Y[nm] * P
            a = self.S(BX - 0.9 * P, y)
            b = self.S(BX + (NCOL + 0.9) * P, y)
            self.cv.create_line(a[0], a[1], b[0], b[1], fill=col, width=max(1, int(1.6 * self.zoom)), tags=getattr(self, '_tag', 'dyn'))
            self._t(BX - 1.1 * P, y, '+' if nm.endswith('+') else '−', 10, col, anchor='e', bold=True)
        self._r(BX - 1.2 * P, BY + 7.6 * P, BX + (NCOL + 1.2) * P, BY + 8.0 * P, fill=C_BOARD2, outline='#b9b4a6')
        rr = 0.3 * P
        for h in self.holes:
            hx, hy = hole_pos(h)
            a = self.S(hx - rr, hy - rr)
            b = self.S(hx + rr, hy + rr)
            self.cv.create_rectangle(a[0], a[1], b[0], b[1], fill=C_HOLE, outline='#8e8a80')
        for c in range(1, NCOL + 1):
            if c % 5 == 0 or c == 1:
                self._t(BX + c * P, BY + 2.2 * P, str(c), 8, '#7d786c', anchor='center')
                self._t(BX + c * P, BY + 13.5 * P, str(c), 8, '#7d786c', anchor='center')
        for r in ROWS_L + ROWS_R:
            self._t(BX - 0.8 * P, BY + ROW_Y[r] * P, r, 8, '#7d786c', anchor='e')
            self._t(BX + (NCOL + 0.8) * P, BY + ROW_Y[r] * P, r, 8, '#7d786c', anchor='w')
        self._t(BX - 1.3 * P, y1 + 0.3 * P, '1. breadboard', 9, '#8d959c')
        if self.carry or self.pending:
            h = self.nearest_hole(*self.mouse)
            if h:
                hx, hy = hole_pos(h)
                a = self.S(hx - 0.5 * P, hy - 0.5 * P)
                b = self.S(hx + 0.5 * P, hy + 0.5 * P)
                self.cv.create_rectangle(a[0], a[1], b[0], b[1], outline=C_ACC, width=2)
                node = node_of(h)
                q = self.S(hx, hy - 0.95 * P)
                self._plate_text(q[0], q[1], self._node_name(h), max(9, 10 * self.zoom), C_ACC)

    def _node_name(self, h):
        if h[0] == 'rail':
            return {'T+': '+', 'T-': '−', 'B+': '+', 'B-': '−'}[h[1]] + ' rail'
        return '%s%d' % (h[2], h[1])

    def _draw_microbit(self):
        """Item 3, drawn from the photograph on page Q2-2: the black micro:bit
        with its two yellow corner triangles, gold touch logo, 5x5 LED matrix,
        buttons A and B and the gold edge connector; below it the cream
        expansion shield (3a) with its black edge socket and the three rows of
        S / V / G header pins; and the AAA battery holder (3e) whose plug has
        to be pushed into the shield."""
        w = self.w
        bx, by = (292.0, 30.0)
        PW = 300.0
        self._r(bx, by, bx + PW, by + 392, fill='#2b2f36', outline='#454b54', width=2)
        if self._roomy():
            self._t(bx + 8, by + 5, '3. Micro:bit kit (#%d)' % (w.active + 1), 9, '#aeb6bd')
        mx, my = (bx + (PW - 240) / 2, by + 26)
        MW, MH = (240.0, 194.0)
        self._r(mx, my, mx + MW, my + MH, fill=DEV_COL[w.active], outline=DEV_EDGE[w.active], width=2)
        # micro-USB, the battery socket and the reset button sit along the
        # top edge, exactly as on the real board
        for k in range(4):                       # the yellow edge triangles
            a = self.S(mx + 8 + k * 26, my)
            b = self.S(mx + 30 + k * 26, my + 17)
            self.cv.create_polygon(a[0], a[1], b[0], a[1], (a[0] + b[0]) / 2, b[1], fill='#f2b826', outline='', tags=getattr(self, '_tag', 'dyn'))
        self._r(mx, my, mx + 10, my + 18, fill='#f2b826', outline='')
        a = self.S(mx + MW / 2 - 17, my + 22)
        b = self.S(mx + MW / 2 + 17, my + 42)
        self.cv.create_oval(a[0], a[1], b[0], b[1], outline='#d8a72a', width=2, tags=getattr(self, '_tag', 'dyn'))
        for dx in (-8, 8):
            c = self.S(mx + MW / 2 + dx, my + 32)
            r = 3.4 * self.zoom
            self.cv.create_oval(c[0] - r, c[1] - r, c[0] + r, c[1] + r, fill='#d8a72a', outline='', tags=getattr(self, '_tag', 'dyn'))
        self._matrix_org = (mx + MW / 2 - 44, my + 56)
        for r_ in range(5):
            for c_ in range(5):
                self._r(self._matrix_org[0] + c_ * 20, self._matrix_org[1] + r_ * 17, self._matrix_org[0] + c_ * 20 + 8, self._matrix_org[1] + r_ * 17 + 12, fill='#4a2018', outline='')
        # black tactile switches with a metal plunger, silkscreened A and B
        for lab, dx in (('A', 14), ('B', MW - 38)):
            self._r(mx + dx, my + 86, mx + dx + 24, my + 110, fill='#15181c', outline='#3a4048')
            c = self.S(mx + dx + 12, my + 98)
            r = 6.5 * self.zoom
            self.cv.create_oval(c[0] - r, c[1] - r, c[0] + r, c[1] + r, fill='#c9ced4', outline='#7d848a', tags=getattr(self, '_tag', 'dyn'))
            t1 = self.S(mx + dx + 4, my + 116)
            t2 = self.S(mx + dx + 16, my + 116)
            t3 = self.S(mx + dx + 10, my + 124)
            self.cv.create_polygon(t1[0], t1[1], t2[0], t2[1], t3[0], t3[1], fill='#f2b826', outline='', tags=getattr(self, '_tag', 'dyn'))
            if self._roomy():
                self._t(mx + dx + 12, my + 132, lab, 9, '#e8eef2', anchor='center', bold=True)
        self.zone_btnA = (mx + 14, my + 86, mx + 38, my + 110)
        self.zone_btnB = (mx + MW - 38, my + 86, mx + MW - 14, my + 110)
        self._r(mx, my + MH - 26, mx + MW, my + MH, fill='#c9a227', outline='#8a6f18')
        for k in range(28):
            self._r(mx + 5 + k * (MW - 10) / 28, my + MH - 24, mx + 9 + k * (MW - 10) / 28, my + MH, fill='#e0bd45', outline='')
        # the five big pads are rings: gold annulus, hole right through
        for k, lab in enumerate(('0', '1', '2', '3V', 'G')):
            cxp = mx + 16 + k * (MW - 32) / 4.0
            c = self.S(cxp, my + MH - 13)
            r1 = 11 * self.zoom
            r2 = 5.4 * self.zoom
            self.cv.create_oval(c[0] - r1, c[1] - r1, c[0] + r1, c[1] + r1,
                                fill='#e0bd45', outline='#8a6f18', tags=getattr(self, '_tag', 'dyn'))
            self.cv.create_oval(c[0] - r2, c[1] - r2, c[0] + r2, c[1] + r2,
                                fill='#15181c', outline='#8a6f18', tags=getattr(self, '_tag', 'dyn'))
            if self._roomy():
                self._t(cxp, my + MH - 34, lab, 7, '#d8c894', anchor='center', bold=True)
        sx, sy = (bx + 16, my + MH - 10)
        SW, SH = (PW - 32, 104.0)
        self._r(sx, sy + 16, sx + SW, sy + SH, fill='#efe9dc', outline='#b8b09c', width=2)
        # the edge-connector socket: the board is pushed down into it, so the
        # bottom of the fingers disappears inside
        kx0, kx1 = (mx - 16, mx + MW + 16)
        self._r(kx0, sy, kx1, sy + 22, fill='#15181c', outline='#000')
        self._r(kx0 + 5, sy + 3, kx1 - 5, sy + 9, fill='#0a0c0f', outline='')
        self._r(kx0, sy + 18, kx1, sy + 22, fill='#2a2f36', outline='')
        for ex in (kx0 + 4, kx1 - 10):
            self._r(ex, sy - 6, ex + 6, sy + 4, fill='#8d949b', outline='#5c6167')
        if self._roomy():
            self._t(sx + 6, sy + SH - 12, '3a', 8, '#6c6553')
        # every pin is broken out three times: S is the pin itself, V is 3V,
        # G is 0V - that is where a jumper actually goes
        HX, HP = (sx + 30, 14.0)
        self.zone_hdr = []
        self.hdr_pos = {}
        for r_, row in enumerate(HDR_ROWS):
            py = sy + 38 + r_ * 18
            if self._roomy():
                self._t(HX - 11, py, row, 7, '#6c6553', anchor='e')
            for k in range(HDR_COLS):
                px = HX + k * HP
                # the pins are in the colours of the jumpers this kit came with
                if row == 'V':
                    col = self.wire('w2')
                elif row == 'G':
                    col = self.wire('w3')
                else:
                    col = self.wire('w1')
                self._r(px - 4.5, py - 7, px + 4.5, py + 7, fill=col, outline='#8d8674')
                self._r(px - 2, py - 2.6, px + 2, py + 2.6, fill='#15181c', outline='')
                self.hdr_pos[(k, row)] = (px, py)
                self.zone_hdr.append((k, row, (px - 7, py - 10, px + 7, py + 10)))
            # no label past the last pin: it ran off the edge of the shield
        if self._roomy():
            for k in range(0, HDR_COLS, 2):
                self._t(HX + k * HP, sy + 26, str(k), 6, '#6c6553', anchor='center')
        px0, py0 = (sx + SW - 40, sy + SH - 18)
        self._r(px0, py0, px0 + 34, py0 + 18, fill='#1b1e22', outline='#000')
        self._t(px0 + 17, py0 + 9, 'PWR', 6, '#9aa3ab', anchor='center')
        self.zone_socket = (px0, py0, px0 + 34, py0 + 18)
        hx, hy = (bx + 16, by + 322)
        k = w.active
        self._r(hx, hy, hx + 150, hy + 54, fill='#dfe4e6', outline='#9aa0a6', width=2)
        self.zone_slot = []
        for c in range(2):
            cy = hy + 10 + c * 22
            loaded = w.cells[k] > c
            self._r(hx + 12, cy, hx + 108, cy + 16, fill='#c9c2ad' if loaded else '#9aa0a6', outline='#8d8674' if loaded else '#6f767c')
            if loaded:
                self._r(hx + 108, cy + 4, hx + 114, cy + 12, fill='#b9b2a0', outline='#8d8674')
                if self._roomy():
                    self._t(hx + 60, cy + 8, 'AAA  1.5V', 6, '#5d574a', anchor='center')
            else:
                if self._roomy():
                    self._t(hx + 60, cy + 8, 'empty', 6, '#e6ecef', anchor='center')
            self.zone_slot.append((hx + 12, cy, hx + 114, cy + 16))
        if self._roomy():
            self._t(hx + 4, hy + 58, '3e (%s)' % DEV_NAME[k], 8, '#7b838b')
        wx0, wy0 = (40.0, 164.0)
        if self._roomy():
            self._t(wx0, wy0 - 14, 'three jumpers - take one, then a header and a hole', 7, '#9aa3ab')
        self.zone_wire = []
        for i2, wid in enumerate(WIRES):
            j = w.jump[wid]
            if j['hdr'] or j['hole'] or (self.carry and self.carry[0] == 'wire' and self.carry[1] == wid):
                continue
            x = wx0 + i2 * 54
            self._r(x, wy0, x + 44, wy0 + 8, fill=self.wire(wid), outline=self.case(wid))
            self.zone_wire.append((wid, (x - 2, wy0 - 6, x + 46, wy0 + 14)))
        tx0, ty0 = (40.0, 88.0)
        if self._roomy():
            self._t(tx0, ty0 - 12, 'loose AAA cells (six in all, two per kit)', 7, '#9aa3ab')
        self.zone_cell = []
        for c in range(6):
            x = tx0 + c * 40
            avail = c < w.cells_free
            self._r(x, ty0, x + 34, ty0 + 14, fill='#c9c2ad' if avail else '#3a4048', outline='#8d8674' if avail else '#2b2f36')
            if avail:
                self._r(x + 34, ty0 + 4, x + 39, ty0 + 10, fill='#b9b2a0', outline='#8d8674')
            self.zone_cell.append((x, ty0, x + 39, ty0 + 14))
        self._r(hx + 120, hy + 14, hx + 144, hy + 40, fill='#2b2f36', outline='#11141a')
        on = w.switch[k]
        self._r(hx + 123 + (12 if on else 0), hy + 17, hx + 135 + (12 if on else 0), hy + 37, fill='#2f6f3f' if on else '#8d949b', outline='#11141a')
        self._t(hx + 132, hy + 46, 'ON' if on else 'OFF', 7, '#7dffb0' if on else '#9aa3ab', anchor='center')
        self.zone_switch = (hx + 120, hy + 14, hx + 144, hy + 40)
        a = self.S(hx + 150, hy + 20)
        if w.batt_in[k]:
            b = self.S(px0 + 17, py0 + 9)
            mid = self.S(hx + 190, hy + 4)
        else:
            b = self.S(hx + 196, hy + 30)
            mid = self.S(hx + 180, hy + 46)
        cab = CABLE_SETS[w.active]
        for col, off in ((cab['a'], -3), (cab['b'], 3)):
            self.cv.create_line(a[0], a[1] + off, mid[0], mid[1] + off, b[0], b[1] + off, smooth=True, fill=col, width=max(2, int(2.4 * self.zoom)), tags=getattr(self, '_tag', 'dyn'))
        if w.batt_in[k]:                 # seated: it covers the socket whole
            q1 = self.S(px0 - 2, py0 - 2)
            q2 = self.S(px0 + 36, py0 + 20)
            plug = (q1[0], q1[1], q2[0], q2[1])
        else:
            pw, ph = (22.0, 15.0)
            plug = (b[0] - pw * self.zoom / 2, b[1] - ph * self.zoom / 2,
                    b[0] + pw * self.zoom / 2, b[1] + ph * self.zoom / 2)
        self.cv.create_rectangle(*plug, fill='#cdd3d6' if w.batt_in[k] else '#f2f2f0', outline='#8d949b', width=2)
        if w.batt_in[k]:
            self.cv.create_rectangle(plug[0] + 3, plug[1] + 3, plug[2] - 3,
                                     plug[1] + (plug[3] - plug[1]) * 0.42,
                                     fill='#b6bcc2', outline='', tags=getattr(self, '_tag', 'dyn'))
        self.plug_px = plug
        # the plug hint would run off the panel; the status list already says it
        if self._roomy():
            self._t(bx + PW - 12, by + 5, 'A:P0  B:P1', 7, '#7b838b', anchor='e')

    def _draw_matrix(self):
        """only the lit LEDs have to be redrawn every frame."""
        org = getattr(self, '_matrix_org', None)
        if not org:
            return
        cells = self._matrix_cells()
        for r_ in range(5):
            for c_ in range(5):
                if cells[r_][c_]:
                    self._r(org[0] + c_ * 20, org[1] + r_ * 17, org[0] + c_ * 20 + 8, org[1] + r_ * 17 + 12, fill='#ff3320', outline='')

    def _matrix_cells(self):
        cells = [[0] * 5 for _ in range(5)]
        if self.scroll is None:
            return cells
        txt, t0 = self.scroll
        cols = []
        for ch in txt:
            pat = FONT5.get(ch, FONT5['?'])
            for c in range(5):
                cols.append([1 if pat[r][c] == '1' else 0 for r in range(5)])
            cols.append([0] * 5)
        cols = [[0] * 5 for _ in range(5)] + cols + [[0] * 5 for _ in range(5)]
        step = 0.13
        k = int((time.perf_counter() - t0) / step)
        if k > len(cols) - 5:
            self.scroll = None
            return cells
        for c in range(5):
            col = cols[k + c] if k + c < len(cols) else [0] * 5
            for r in range(5):
                cells[r][c] = col[r]
        return cells

    def _draw_battery(self):
        pass

    def _draw_resistors(self):
        w = self.w
        for cid, (h1, h2) in w.placed.items():
            p1, p2 = (hole_pos(h1), hole_pos(h2))
            a, b = (self.S(*p1), self.S(*p2))
            self.cv.create_line(a[0], a[1], b[0], b[1], fill='#b9bfc6', width=max(1, int(0.16 * P * self.zoom)), tags=getattr(self, '_tag', 'dyn'))
            mx, my = ((p1[0] + p2[0]) / 2.0, (p1[1] + p2[1]) / 2.0)
            L = math.hypot(p2[0] - p1[0], p2[1] - p1[1])
            ang = math.atan2(p2[1] - p1[1], p2[0] - p1[0])
            bl = min(0.62 * L, 1.5 * P)
            bw = 0.34 * P
            kind, col = (None, None)
            for items in PACKS.values():
                for c2, nom, kd, cl in items:
                    if c2 == cid:
                        kind, col = (kd, cl)
            pts = []
            for dx, dy in ((-bl / 2, -bw / 2), (bl / 2, -bw / 2), (bl / 2, bw / 2), (-bl / 2, bw / 2)):
                rx = mx + dx * math.cos(ang) - dy * math.sin(ang)
                ry = my + dx * math.sin(ang) + dy * math.cos(ang)
                pts += list(self.S(rx, ry))
            self.cv.create_polygon(*pts, fill=col if kind == 'tube' else '#d9c39a', outline='#5c5347', width=1, tags=getattr(self, '_tag', 'dyn'))
            if kind != 'tube':
                for f in (-0.28, -0.12, 0.06, 0.26):
                    bx0 = mx + f * bl * math.cos(ang)
                    by0 = my + f * bl * math.sin(ang)
                    q1 = self.S(bx0 - bw / 2 * math.sin(ang) * -1, by0 + bw / 2 * math.cos(ang) * -1)
                    q2 = self.S(bx0 + bw / 2 * math.sin(ang) * -1, by0 - bw / 2 * math.cos(ang) * -1)
                    self.cv.create_line(q1[0], q1[1], q2[0], q2[1], fill='#3a3f46', width=max(1, int(0.09 * P * self.zoom)), tags=getattr(self, '_tag', 'dyn'))
            q = self.S(mx, my - 0.68 * P)
            self._plate_text(q[0], q[1], cid, max(8, 9 * self.zoom), '#c7ced5')

    def _draw_loose_wire(self, key):
        """a jumper with only one end in place dangles from it"""
        j = self.w.jump[key]
        if not j['hdr'] and (not j['hole']):
            return
        p0 = self.hdr_pos.get(tuple(j['hdr'])) if j['hdr'] else hole_pos(j['hole'])
        if not p0:
            return
        st = LOOSE_STUB[WIRES.index(key)]
        a = self.S(*p0)
        b = self.S(p0[0] + st[2], p0[1] + st[3])
        c = self.S(p0[0] + st[0], p0[1] + st[1])
        wdt = max(2, int(0.16 * P * self.zoom))
        tg = getattr(self, '_tag', 'dyn')
        for col, ww in ((self.case(key), wdt + 3), (self.wire(key), wdt)):
            self.cv.create_line(a[0], a[1], c[0], c[1], b[0], b[1],
                                smooth=True, fill=col, width=ww, tags=tg)
        r = 0.24 * P * self.zoom
        self.cv.create_oval(a[0] - r, a[1] - r, a[0] + r, a[1] + r,
                            fill=self.wire(key), outline='#0c1218', tags=tg)

    def _draw_wires(self):
        w = self.w
        for key in WIRES:
            j = w.jump[key]
            if not j['hdr'] or not j['hole']:
                self._draw_loose_wire(key)
                continue
            p0 = self.hdr_pos.get(tuple(j['hdr']))
            if not p0:
                continue
            p1 = hole_pos(j['hole'])
            a, b = (self.S(*p0), self.S(*p1))
            mid = self.S((p0[0] + p1[0]) / 2 + 40, (p0[1] + p1[1]) / 2 + 60)
            wdt = max(2, int(0.16 * P * self.zoom))
            tg = getattr(self, '_tag', 'dyn')
            self.cv.create_line(a[0], a[1], mid[0], mid[1], b[0], b[1], smooth=True, fill=self.case(key), width=wdt + 3, tags=tg)
            self.cv.create_line(a[0], a[1], mid[0], mid[1], b[0], b[1], smooth=True, fill=self.wire(key), width=wdt, tags=tg)
            r = 0.24 * P * self.zoom
            self.cv.create_oval(b[0] - r, b[1] - r, b[0] + r, b[1] + r, fill=self.wire(key), outline='#0c1218', tags=tg)
            self.cv.create_oval(a[0] - r * 0.8, a[1] - r * 0.8, a[0] + r * 0.8, a[1] + r * 0.8,
                                fill=self.wire(key), outline='#0c1218', tags=tg)
            self._plate_text(b[0] + 18, b[1] - 14, hdr_name(j['hdr'][0], j['hdr'][1]),
                             max(9, 10 * self.zoom),
                             '#8fb4f0' if j['hdr'][1] == 'G' else self.wire(key))

    def _draw_carry(self):
        px, py = self.mouse
        if self.carry_cell:
            self.cv.create_rectangle(px + 8, py - 7, px + 42, py + 7, fill='#c9c2ad', outline='#8d8674', tags='dyn')
            self.cv.create_rectangle(px + 42, py - 3, px + 47, py + 3, fill='#b9b2a0', outline='#8d8674', tags='dyn')
            self._plate_text(px + 8 + 60, py - 14, 'AAA cell: click an empty bay', 9, C_ACC)
        if self.carry and self.carry[0] == 'res':
            self._plate_text(px + 16 + 60, py - 14, 'resistor %s : click the first hole' % self.carry[1], 10, C_ACC)
        elif self.carry and self.carry[0] == 'wire':
            self._plate_text(px + 16 + 60, py - 14, LEAD_LABEL[self.carry[1]] + CARRY_TAIL, 10, C_ACC)
        if self.pending:
            p = self.S(*hole_pos(self.pending))
            self.cv.create_line(p[0], p[1], px, py, fill=C_ACC, dash=(4, 3), width=2, tags=getattr(self, '_tag', 'dyn'))

    def _in(self, z, x, y):
        return z and z[0] <= x <= z[2] and (z[1] <= y <= z[3])

    def _sz(self, z):
        """scene rect -> screen rect"""
        a = self.S(z[0], z[1])
        b = self.S(z[2], z[3])
        return (a[0], a[1], b[0], b[1])

    def _hpx(self, r, minpx=20):
        """screen rect, grown so it is never smaller than minpx"""
        x0, y0, x1, y1 = r
        if x1 - x0 < minpx:
            c = (x0 + x1) / 2.0
            x0, x1 = (c - minpx / 2.0, c + minpx / 2.0)
        if y1 - y0 < minpx:
            c = (y0 + y1) / 2.0
            y0, y1 = (c - minpx / 2.0, c + minpx / 2.0)
        return (x0, y0, x1, y1)

    def _hz(self, z, minpx=20):
        return self._hpx(self._sz(z), minpx)

    def _pick_nearest(self, zones, x, y, rmax):
        """neighbouring controls sit closer than the enlarged zones, so the
           nearest centre wins"""
        best, bd = (None, rmax * rmax)
        for key, z in zones:
            r = self._sz(z)
            cx, cy = ((r[0] + r[2]) / 2.0, (r[1] + r[3]) / 2.0)
            d = (cx - x) ** 2 + (cy - y) ** 2
            if d <= bd:
                best, bd = (key, d)
        return best

    def _wire_at(self, px, py, rmax=12.0):
        """the drawn wire is a target along its whole length"""
        best, bd = (None, rmax * rmax)
        for key in WIRES:
            j = self.w.jump[key]
            if not j['hdr'] and (not j['hole']):
                continue
            if j['hdr'] and j['hole']:
                p0 = self.hdr_pos.get(tuple(j['hdr']))
                if not p0:
                    continue
                p1 = hole_pos(j['hole'])
                mm = ((p0[0] + p1[0]) / 2.0 + 40, (p0[1] + p1[1]) / 2.0 + 60)
            else:                       # one end still free: the hanging stub
                p0 = self.hdr_pos.get(tuple(j['hdr'])) if j['hdr'] else hole_pos(j['hole'])
                if not p0:
                    continue
                st = LOOSE_STUB[WIRES.index(key)]
                p1 = (p0[0] + st[2], p0[1] + st[3])
                mm = (p0[0] + st[0], p0[1] + st[1])
            a = self.S(*p0)
            b = self.S(*p1)
            m = self.S(*mm)
            for i in range(25):
                u = i / 24.0
                v = 1.0 - u
                qx = v * v * a[0] + 2 * v * u * m[0] + u * u * b[0]
                qy = v * v * a[1] + 2 * v * u * m[1] + u * u * b[1]
                d = (qx - px) ** 2 + (qy - py) ** 2
                if d <= bd:
                    best, bd = (key, d)
        return best

    def _roomy(self):
        """below this zoom a caption is wider than the gap it was laid out in,
           so it would print on top of the parts; the side panel says it all
           anyway"""
        return self.zoom >= 0.85

    def _plate_text(self, px, py, txt, size, fill):
        """a label that has to sit over the board gets its own plate"""
        f = ('Malgun Gothic', max(8, int(size)), 'normal')
        tg = getattr(self, '_tag', 'dyn')
        t = self.cv.create_text(px, py, text=txt, fill=fill, font=f, tags=tg)
        x0, y0, x1, y1 = self.cv.bbox(t)
        r = self.cv.create_rectangle(x0 - 3, y0 - 2, x1 + 3, y1 + 2,
                                     fill='#12151a', outline='', tags=tg)
        self.cv.tag_raise(t, r)
        return t

    def on_motion(self, e):
        self.mouse = (e.x, e.y)
        if getattr(self, 'dragging_plug', False):
            w = self.w
            if self._in(self._sz(self.zone_socket), e.x, e.y):
                w.batt_in[w.active] = True
                self.dragging_plug = False
                self.say('Battery plugged into PWR; now switch it on.')

    def take_resistor(self, cid):
        if cid in self.w.placed:
            self.say('Already on the breadboard; right-click it to pull it out.')
            return
        self.carry = ('res', cid)
        self.pending = None
        self.say('Click the hole for the first lead.')

    def _free_hand(self, what):
        """holding a cell and a jumper at once used to make one click do two
        things; only one thing can be in hand."""
        w = self.w
        if what != 'cell' and w.cell_hand:
            w.cells_free += 1
            self.carry_cell = False
        if what == 'cell' and self.carry:
            self.carry = None
            self.pending = None

    def on_click(self, e):
        x, y = (e.x, e.y)
        self.mouse = (x, y)
        w = self.w
        k = w.active
        spare = self._pick_nearest(list(getattr(self, 'zone_wire', [])), x, y, 16.0)
        if spare is not None:
            self._free_hand('wire')
            self.carry = ('wire', spare)
            self.pending = None
            self.say(LEAD_LABEL[spare] + TAKE_MSG)
            return
        if self._in(self._hz(self.zone_switch, 26), x, y):
            w.switch[k] = not w.switch[k]
            self.say('Battery holder switched %s.' % ('on' if w.switch[k] else 'off'))
            return
        c = self._pick_nearest(list(enumerate(getattr(self, 'zone_slot', []))), x, y, 20.0)
        if c is not None:
            self._free_hand('cell')
            if True:
                if w.cells[k] > c:
                    w.unload_cell(k)
                    self.carry_cell = False
                    self.say('Cell taken out and put back on the bench.')
                elif not self.carry_cell:
                    self.say('Pick a loose cell up from the bench first.')
                else:
                    w.cells[k] += 1
                    self.carry_cell = False
                    self.say('%d of 2 cells fitted.' % w.cells[k])
                return
        c = self._pick_nearest(list(enumerate(getattr(self, 'zone_cell', []))), x, y, 18.0)
        if c is not None:
            self._free_hand('cell')
            if self.carry_cell:
                w.cells_free += 1
                self.carry_cell = False
                self.say('Cell put back on the bench.')
            elif w.cells_free > 0:
                w.cells_free -= 1
                self.carry_cell = True
                self.say('Cell in hand: click an empty bay of the holder.')
            return
        if self.plug_px and self._in(self._hpx(self.plug_px, 26), x, y):
            self.dragging_plug = True
            return
        if self._in(self._hz(self.zone_btnA, 28), x, y):
            self.press_button('A')
            return
        if self._in(self._hz(self.zone_btnB, 28), x, y):
            self.press_button('B')
            return
        hd = self._pick_nearest([((c2, r2), z) for c2, r2, z in getattr(self, 'zone_hdr', [])], x, y, 11.0)
        if hd is not None:
            self._free_hand('wire')
            col, row = hd
            there = w.wire_at_hdr(col, row)
            if self.carry and self.carry[0] == 'wire':
                wid = self.carry[1]
                if there and there != wid:
                    self.say(HDR_TAKEN)
                    return
                w.jump[wid]['hdr'] = (col, row)
                if w.jump[wid]['hole']:
                    self.carry = None
                    self.say(LEAD_LABEL[wid] + ' : ' + hdr_name(col, row) + ARROW + self._node_name(w.jump[wid]['hole']))
                else:
                    self.say(LEAD_LABEL[wid] + INTO_HDR + hdr_name(col, row))
                return
            if there:
                self.carry = ('wire', there)
                w.jump[there]['hdr'] = None
                self.say(LEAD_LABEL[there] + TAKE_MSG)
                return
            free = w.free_wire()
            if free is None:
                self.say(NO_FREE)
                return
            w.jump[free]['hdr'] = (col, row)
            self.carry = ('wire', free)
            self.say(LEAD_LABEL[free] + INTO_HDR + hdr_name(col, row))
            return
        if not self.carry:
            key = self._wire_at(x, y)
            if key is not None:
                self._free_hand('wire')
                j = w.jump[key]
                if j['hdr'] and j['hole']:     # both ends in: drop the nearer
                    ph = self.S(*self.hdr_pos[tuple(j['hdr'])])
                    pb = self.S(*hole_pos(j['hole']))
                    dh = (ph[0] - x) ** 2 + (ph[1] - y) ** 2
                    db = (pb[0] - x) ** 2 + (pb[1] - y) ** 2
                    if dh <= db:
                        j['hdr'] = None
                    else:
                        j['hole'] = None
                self.carry = ('wire', key)
                self.pending = None
                self.say(LEAD_LABEL[key] + TAKE_MSG)
                return
        h = self.nearest_hole(x, y)
        if self.carry and self.carry[0] == 'wire':
            if h:
                wid = self.carry[1]
                w.jump[wid]['hole'] = h
                if w.jump[wid]['hdr']:
                    self.carry = None
                    self.say(LEAD_LABEL[wid] + ' : ' + hdr_name(w.jump[wid]['hdr'][0], w.jump[wid]['hdr'][1]) + ARROW + self._node_name(h))
                else:
                    self.say(LEAD_LABEL[wid] + INTO_BOARD + self._node_name(h))
            return
        if self.carry and self.carry[0] == 'res':
            if not h:
                return
            if self.pending is None:
                self.pending = h
                self.say('Click the hole for the second lead.')
            else:
                if node_of(h) == node_of(self.pending):
                    self.say('Both leads in the same node would short the resistor.')
                    return
                w.place(self.carry[1], self.pending, h)
                self.pack_btn[self.carry[1]].config(relief='sunken')
                self.carry = None
                self.pending = None
                self.say('')
            return
        cid = self._resistor_at(x, y)
        if cid:
            self.w.remove(cid)
            self.pack_btn[cid].config(relief='flat')
            self.say('Resistor %s removed.' % cid)
            return
        self._lp0 = (x, y)

    def _resistor_at(self, px, py):
        for cid, (h1, h2) in self.w.placed.items():
            p1, p2 = (hole_pos(h1), hole_pos(h2))
            m = self.S((p1[0] + p2[0]) / 2.0, (p1[1] + p2[1]) / 2.0)
            if abs(m[0] - px) < 0.8 * P * self.zoom and abs(m[1] - py) < 0.5 * P * self.zoom:
                return cid
        return None

    def on_rclick(self, e):
        if self.carry or self.pending:
            self.carry = None
            self.pending = None
            return
        key = self._wire_at(e.x, e.y)
        if key is not None:
            self.w.jump[key] = {'hdr': None, 'hole': None}
            self.say(LEAD_LABEL[key] + PULLED_OUT)
            return
        hd = self._pick_nearest([((c2, r2), z) for c2, r2, z in getattr(self, 'zone_hdr', [])], e.x, e.y, 11.0)
        if hd is not None:
            at = self.w.wire_at_hdr(hd[0], hd[1])
            if at:
                self.w.jump[at] = {'hdr': None, 'hole': None}
                self.say(LEAD_LABEL[at] + PULLED_OUT)
                return
        cid = self._resistor_at(e.x, e.y)
        if cid:
            self.w.remove(cid)
            self.pack_btn[cid].config(relief='flat')
            return
        h = self.nearest_hole(e.x, e.y)
        if h:
            for key in WIRES:
                hh = self.w.jump[key]['hole']
                if hh == h:
                    self.w.jump[key] = {'hdr': None, 'hole': None}
                    self.say(LEAD_LABEL[key] + PULLED_OUT)
                    return

    def on_wheel(self, e, direction=None):
        d = direction if direction is not None else 1 if e.delta > 0 else -1
        self._view_touched = True
        x0, y0 = self.inv(e.x, e.y)
        self.zoom = max(0.5, min(3.0, self.zoom * (1.12 if d > 0 else 1 / 1.12)))
        x1, y1 = self.inv(e.x, e.y)
        self.pan[0] += (x1 - x0) * self.zoom
        self.pan[1] += (y1 - y0) * self.zoom

    def on_pan_start(self, e):
        self._view_touched = True
        self._p0 = (e.x, e.y, self.pan[0], self.pan[1])

    def on_pan_left(self, e):
        """Dragging on bare bench slides the whole picture.  The canvas items are
        simply moved, so nothing has to be drawn again while the mouse travels."""
        if not getattr(self, '_lp0', None):
            return
        dx, dy = (e.x - self._lp0[0], e.y - self._lp0[1])
        if dx == 0 and dy == 0:
            return
        self._lp0 = (e.x, e.y)
        self.pan = [self.pan[0] + dx, self.pan[1] + dy]
        self.cv.move('all', dx, dy)
        self._skey = self._static_key()

    def on_pan_left_end(self, e):
        self._lp0 = None

    def on_pan(self, e):
        if hasattr(self, '_p0'):
            x0, y0, a, b = self._p0
            self.pan = [a + e.x - x0, b + e.y - y0]

    def press_button(self, which='A'):
        w = self.w
        k = w.active
        if w.cells[k] < 2:
            self.say('This kit needs two AAA cells in its holder (only %d fitted).' % w.cells[k])
            return
        if not w.batt_in[k]:
            self.say('The battery holder is not plugged in: push its plug into PWR.')
            return
        r = self.w.measure(which)
        if r == 'off':
            self.say('The battery holder is switched off.')
            return
        if r == 'novc':
            self.say('nothing is on the 3V header, so the circuit has no supply.')
            return
        if r == 'nognd':
            self.say('nothing is on the GND header, so there is no reference.')
            return
        if r == 'nowire':
            self.say('the circuit is open.')
            return
        if r == 'dead':
            self.say('This micro:bit is damaged: connect another one or ask for the spare.')
            self.scroll = ('Err', time.perf_counter())
            return
        if r == 'short':
            self.scroll = ('Err', time.perf_counter())
            self.say('Short circuit!  Vc and GND were joined without a load; the kit is damaged.')
            self.ask_spare()
            return
        pin = BTN_PIN.get(which or 'A', 0)
        if self.w.roles()['pin'].get(pin) is None:
            self.say('P' + str(pin) + FLOAT_MSG)
        self.last_reading = r
        self.scroll = (str(r), time.perf_counter())

    def ask_spare(self):
        if self.w.spare_used:
            messagebox.showwarning(APP_TITLE, 'Only one replacement per candidate is provided.')
            return
        if messagebox.askyesno(APP_TITLE, 'Ask the invigilator for the replacement kit? (once only)'):
            self.w.spare_used = True
            self.w.dev.dead = False
            self.say('Replacement kit received.')

    def swap_device(self):
        self.w.active = self.dev_var.get()
        self.say('Micro:bit #%d is now wired up.' % (self.w.active + 1))

    def say(self, m):
        self.w.msg = m

    def _tick(self):
        if not self.winfo_exists():
            return
        if self.cv.winfo_width() > 10:
            self.draw()
        self._status()
        self.after(40, self._tick)

    def _status(self):
        w = self.w
        L = []
        R = w.roles()
        miss = []
        if not R['vc']:
            miss.append('3V')
        if not R['gnd']:
            miss.append('GND')
        if R['pin'].get(0) is None:
            miss.append('P0')
        if miss:
            L.append('headers still empty : ' + ', '.join(miss))
        L.append('Expansion header: row S is P0-P16, row V is 3V, row G is GND. The program only ever reads P0 (button A) and P1 (button B).')
        if w.cells[w.active] < 2:
            L.append('cells %d of 2 fitted, %d loose' % (w.cells[w.active], w.cells_free))
        elif not w.batt_in[w.active]:
            L.append('the battery plug is not in the PWR socket')
        elif not w.switch[w.active]:
            L.append('battery holder switch : OFF')
        if w.dev.dead:
            L.append('⚠ ' + 'the current micro:bit is damaged')
        L.append('System check: with the P0 jumper on the GND node it should read ~0, on the 3V node ~1023.')
        if w.msg:
            L.append('• ' + w.msg)
        self.status.config(text='\n\n'.join(L))

def main():
    App().mainloop()
if __name__ == '__main__':
    main()